[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
rpc_endpoints = { eth = "https://eth-sepolia.g.alchemy.com/v2/mwHkM74gwkO6kdWQKCYBRWdbDUnhZB7E", arb = "https://arb-sepolia.g.alchemy.com/v2/mwHkM74gwkO6kdWQKCYBRWdbDUnhZB7E", zksync = "https://sepolia.era.zksync.dev"}

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@ccip=lib/ccip/',
    '@chainlink-local/=lib/chainlink-local/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
